### PR TITLE
File org

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Reorganizes Ruby files so that they can be conveniently shared by various other files.

### CODE REVIEW

**Comment by olleolleolle** [comment]
(@BurdetteLamar  Oh, perhaps there's been a rebase too little?)

**Comment by BurdetteLamar** [comment]
> 
> 
> (@BurdetteLamar Oh, perhaps there's been a rebase too little?)

Working on the conflicts, but not sure how to proceed.

**Comment by BurdetteLamar** [comment]
> 
> 
> (@BurdetteLamar Oh, perhaps there's been a rebase too little?)

I'm lost.  Any guidance?

**Comment by olleolleolle** [comment]
@BurdetteLamar I was able to rebase this branch on top of the current master.

<details>

```
git checkout master # Ensure being on master
git fetch # Get latest changes
git reset --hard origin/master # Make sure your local working copy is the same as what is on GitHub
git checkout file_org # Switch to this branch
git rebase origin/master # "Replay" the commits of this branch, on top of the "master" branch
```

The result would be: this branch now has 1 commit. `Reorganize ruby example files`

Now, it'd be possible to overwrite the current file_org branch:

`git push --force`

Now, one could go to GitHub and reload.

<summary>Much Detail Here</summary>

</details>

**Comment by BurdetteLamar** [comment]
> 
> 
> @BurdetteLamar I was able to rebase this branch on top of the current master.
> Much Detail Here

This isn't working for me.  Think I'll delete this PR and repo, clone from master, and start over.

**Comment by olleolleolle** [comment]
@BurdetteLamar Good luck! If you want me to assist in carrying the existing commit into a new PR, I can do that, too. Let me know if you want an assist like that. In any case, good job on this PR!

**Comment by BurdetteLamar** [comment]
> 
> 
> @BurdetteLamar Good luck! If you want me to assist in carrying the existing commit into a new PR, I can do that, too. Let me know if you want an assist like that. In any case, good job on this PR!

Thanks, @olleolleolle, for your time.  I'll just bail out and start over.

**Comment by BurdetteLamar** [comment]
Too fouled up.  Re-doing.

**Pull request closed without merging**
